import { useEffect, useState } from "react";
import { Link, useLocation } from "wouter";
import { ArrowLeft, Save, Loader2, GraduationCap } from "lucide-react";
import { Button } from "@/components/ui/button"; import { Input } from "@/components/ui/input"; import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"; import { PageHeader } from "@/components/ui/page-header"; import { useToast } from "@/hooks/use-toast";
const hdr = () => ({ Authorization:`Bearer ${localStorage.getItem("payroll_nexus_token")}`, "Content-Type":"application/json" });
function Row({label,required,children}:{label:string;required?:boolean;children:any}){return <div className="grid grid-cols-3 gap-4 py-3 border-b last:border-0"><label className="text-sm text-muted-foreground text-right pt-2">{label}{required&&<span className="text-destructive"> *</span>}</label><div className="col-span-2">{children}</div></div>}
export default function GradeFormPage({params}:{params:{code?:string}}){
 const edit=!!params.code; const code=params.code?decodeURIComponent(params.code):undefined; const [,nav]=useLocation(); const {toast}=useToast(); const [saving,setSaving]=useState(false); const [loading,setLoading]=useState(edit); const [error,setError]=useState(""); const [form,setForm]=useState({GradeCode:"",GradeName:"",HraRate:"",GradeRemark:""});
 useEffect(()=>{if(!edit)return; fetch(`/api/grades/${code}`,{headers:hdr()}).then(r=>r.json()).then(d=>{setForm({GradeCode:String(d.GradeCode??""),GradeName:d.GradeName??"",HraRate:d.HraRate==null?"":String(d.HraRate),GradeRemark:d.GradeRemark??""});setLoading(false)}).catch(()=>{setError("Could not load grade");setLoading(false)})},[edit,code]);
 async function submit(e:any){e.preventDefault();setError("");setSaving(true); const payload:any={GradeName:form.GradeName.trim(),HraRate:form.HraRate,GradeRemark:form.GradeRemark.trim()}; if(!edit)payload.GradeCode=form.GradeCode.trim(); try{const r=await fetch(edit?`/api/grades/${code}`:"/api/grades",{method:edit?"PATCH":"POST",headers:hdr(),body:JSON.stringify(payload)});const d=await r.json();if(!r.ok){setError(d.error||"Could not save grade");return;} toast({title:edit?"Grade updated":"Grade created"}); nav(`/grades/${d.GradeCode??code??form.GradeCode}`);}finally{setSaving(false)}}
 if(loading)return <div className="p-6 text-sm text-muted-foreground">Loading grade…</div>;
 return <div className="p-6 space-y-6 max-w-2xl"><div className="flex items-center gap-3"><Button asChild variant="ghost" size="icon"><Link href={edit?`/grades/${code}`:"/grades"}><ArrowLeft className="h-4 w-4"/></Link></Button><PageHeader title={edit?`Edit Grade — ${code}`:"Add Grade"} subtitle="GRADEMASTER" icon={<GraduationCap className="h-5 w-5"/>}/></div>{error&&<div className="border border-destructive/50 bg-destructive/5 text-destructive rounded-md px-4 py-3 text-sm">{error}</div>}<form onSubmit={submit}><Card><CardHeader><CardTitle className="text-sm">Grade Details</CardTitle></CardHeader><CardContent className="space-y-0"><Row label="Grade Code" required><Input value={form.GradeCode} disabled={edit} inputMode="numeric" onChange={e=>setForm({...form,GradeCode:e.target.value.replace(/\D/g,"")})} placeholder="e.g. 1"/></Row><Row label="Grade Name" required><Input value={form.GradeName} onChange={e=>setForm({...form,GradeName:e.target.value})} placeholder="e.g. Grade A"/></Row><Row label="HRA Rate"><Input type="number" min="0" max="100" step="0.01" value={form.HraRate} onChange={e=>setForm({...form,HraRate:e.target.value})} placeholder="e.g. 40"/></Row><Row label="Remark"><Input value={form.GradeRemark} onChange={e=>setForm({...form,GradeRemark:e.target.value})} placeholder="Optional remark"/></Row></CardContent></Card><div className="flex justify-between mt-4 pt-4 border-t"><Button asChild variant="outline"><Link href={edit?`/grades/${code}`:"/grades"}>Cancel</Link></Button><Button disabled={saving} type="submit">{saving?<><Loader2 className="h-4 w-4 mr-2 animate-spin"/>Saving…</>:<><Save className="h-4 w-4 mr-2"/>{edit?"Save Changes":"Create Grade"}</>}</Button></div></form></div>
}
